apiVersion: v1
kind: Service
metadata:
  name: external-nginx
  namespace: default
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 30009
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
