apiVersion: apps/v1
kind: Deployment
metadata:
  name: antifraud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antifraud
  template:
    metadata:
      labels:
        app: antifraud
    spec:
      containers:
      - name: antifraud
        image: ivanmds2/poc_event_driven_antifraud:1.0.10
        resources:
          requests:
            cpu: "250m" 
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
          - name: MONGO_CONNECTION_STRING
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: mongoConnectionString
          - name: KAFKA_BROKER
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: kafkaConnectionString
          - name: COLLECTOR_URI
            value: "http://metric-collector-service:4317"
          - name: IS_GRPC
            value: "YES"