apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: ivanmds/poc_event_driven_customer
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_CONNECTION_STRING
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: mongoConnectionString
          - name: KAFKA_BROKER
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: kafkaConnectionString

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30001