apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: ivanmds2/poc_event_driven_customer:1.0.7
        resources:
          requests:
            cpu: "250m" 
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 3001
        env:
          - name: TOPIC_EXTERNAL_EVENTS
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: topicCustomerExternalEvents
          - name: MONGO_CONNECTION_STRING
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: mongoConnectionString
          - name: KAFKA_BROKER
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: kafkaConnectionString
          - name: OTLP_ENDPOINT
            value: "http://metric-collector-service:4317"

---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
