apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: ivanmds/poc_event_driven_payment:1.0.3
        ports:
        - containerPort: 3002
        env:
          - name: TOPIC_EXTERNAL_EVENTS
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: topicPaymentExternalEvents
          - name: TOPIC_FRAUD_ANALYZE_REQUEST
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: topicPaymentFraudAnalyseRequest
          - name: TOPIC_FRAUD_ANALYZE_RESPONSE
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: topicPaymentFraudAnalyseResponse
          - name: MONGO_CONNECTION_STRING
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: mongoConnectionString
          - name: KAFKA_BROKER
            valueFrom:
              configMapKeyRef:
                name: all-configs
                key: kafkaConnectionString

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment
  type: NodePort
  ports:
    - port: 3002
      nodePort: 30002