apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  config: |
    receivers:
      otlp:
        protocols:
          http:
    
    processors:
      batch:
      
    exporters:
      logging:
        loglevel: debug

      prometheus:
        endpoint: "0.0.0.0:8889"

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check,pprof,zpages]
      telemetry:
        logs:
          level: "debug"

      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, prometheus]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]