apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 6831
        - containerPort: 16686
        - containerPort: 14268
        - containerPort: 14250
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  selector:
    app: jaeger
  ports:
    - name: p1
      protocol: TCP
      port: 6831
      targetPort: 6831
    - name: p2
      protocol: TCP
      port: 16686
      targetPort: 16686
    - name: p3
      protocol: TCP
      port: 14268
      targetPort: 14268
    - name: p4
      protocol: TCP
      port: 14250
      targetPort: 14250


