---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus-config.yaml: |
    global:
      scrape_interval:     2s 
      evaluation_interval: 2s 
      external_labels:
        monitor: 'codelab-monitor'

    scrape_configs:
    - job_name: 'otel-collector'
      scrape_interval: 3s
      static_configs:
      - targets: ['metric-collector-service:8888']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        args:
        - '--config.file=/config/prometheus-config.yaml'
        - '--storage.tsdb.path=/data/prometheus'
        - '--web.enable-remote-write-receiver'
        volumeMounts:
        - mountPath: /config
          name: prometheus-config
        - mountPath: '/data/prometheus'
          name: prometheus-vl
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
        - name: prometheus-vl
          persistentVolumeClaim:
            claimName: observability-pvc
        - name: prometheus-config
          configMap:
            name: prometheus-config
            items:
            - key: prometheus-config.yaml
              path: prometheus-config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090