apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp2
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: gp2
  fsType: ext4
volumeBindingMode: Immediate