apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-deployment
  labels:
    app: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: cassandra
          persistentVolumeClaim:
            claimName: database-pvc
      containers:
      - name: cassandra
        image: openzipkin/zipkin-cassandra
        volumeMounts:
          - mountPath: "/bitnami"
            name: cassandra
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 9042
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  type: NodePort
  selector:
    app: cassandra
  ports:
    - name: port2
      protocol: TCP
      port: 9042
      targetPort: 9042