apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-gp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      volumes:
        - name: mongodb
          persistentVolumeClaim:
            claimName: mongodb-claim
      containers:
      - name: mongodb
        image: mongo
        volumeMounts:
          - mountPath: "/data/db"
            name: mongodb
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 27017  
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: user
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: pwd
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017