apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-otlp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-otlp
  template:
    metadata:
      labels:
        app: customer-otlp
    spec:
      containers:
      - name: customer-otlp
        image: ivanmds2/customer-poc-otlp:1.0.9
        ports: 
          - containerPort: 80
        livenessProbe:
          httpGet:
            path: /api/v1/Customer
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 20
        env:
          - name: COLLECTOR_URI
            value: "metric-collector-service:4318"
          - name: MONGO_CONNECTION
            value: "mongodb://user:pwd@mongo-service:27017/admin"
          - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
            value: http://metric-collector-service:4318
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://metric-collector-service:4318
---
apiVersion: v1
kind: Service
metadata:
  name: customer-otlp-service
spec:
  selector:
    app: customer-otlp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80