apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: nginx
          ports:
          - containerPort: 80