apiVersion: v1
kind: Service
metadata:
  name: nginx-service-test
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: Instance
spec:
  rules:
  - host:
    http:
      paths:
      - path: /nignx
        pathType: Prefix
        backend:
          service:
            name: nginx-service-test
            port:
              number: 30000
